# Example docksal/ci-agent

stages:
  - deploy 
  
deploy_review:
  stage: deploy
  image: docksal/ci-agent:edge-base 
  script:   
    - echo "deploy staging"
    - source /usr/local/bin/build-env
    - build-init
    - ssh docker-host "cd $REMOTE_BUILD_DIR && fin init"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.$CI_PROJECT_NAME.$DOCKSAL_HOST         # Create environment in gitlab, see README.md for $DOCKASL_HOST_IP
    on_stop: stop_review                                                    # Make removal of branches possible
  only:
    - branches
  except:
    - master


# remove review from server. Automatic when branch is deleted, or manual in gitlab.
stop_review:
  stage: deploy
  image: docksal/ci-agent:edge-base 
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Remove review app"
    - source /usr/local/bin/build-env
    - build-init
    - ssh docker-host "cd $REMOTE_BUILD_DIR && fin remove && rm -rf $REMOTE_BUILD_DIR"  # remove docksal environment & code
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

